# Generated by Django 4.1.4 on 2022-12-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='networking',
            name='enodeb_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
